#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriAgrMovModelo;

namespace AriAgrMovModelo	
{
	public partial class AriAgrMod : OpenAccessContext, IAriAgrModUnitOfWork
	{
		private static string connectionStringName = @"AriagroConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public AriAgrMod()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public AriAgrMod(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public AriAgrMod(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public AriAgrMod(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public AriAgrMod(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Variedade> Variedades 
		{
			get
			{
				return this.GetAll<Variedade>();
			}
		}
		
		public IQueryable<Trzlineas_confeccion> Trzlineas_confeccions 
		{
			get
			{
				return this.GetAll<Trzlineas_confeccion>();
			}
		}
		
		public IQueryable<Trzlineas_carga> Trzlineas_cargas 
		{
			get
			{
				return this.GetAll<Trzlineas_carga>();
			}
		}
		
		public IQueryable<Trzdispositivo> Trzdispositivos 
		{
			get
			{
				return this.GetAll<Trzdispositivo>();
			}
		}
		
		public IQueryable<Rsocio> Rsocios 
		{
			get
			{
				return this.GetAll<Rsocio>();
			}
		}
		
		public IQueryable<Rcampo> Rcampos 
		{
			get
			{
				return this.GetAll<Rcampo>();
			}
		}
		
		public IQueryable<Producto> Productos 
		{
			get
			{
				return this.GetAll<Producto>();
			}
		}
		
		public IQueryable<Trzpalet> Trzpalets 
		{
			get
			{
				return this.GetAll<Trzpalet>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
			return backend;
		}
	}
	
	public interface IAriAgrModUnitOfWork : IUnitOfWork
	{
		IQueryable<Variedade> Variedades
		{
			get;
		}
		IQueryable<Trzlineas_confeccion> Trzlineas_confeccions
		{
			get;
		}
		IQueryable<Trzlineas_carga> Trzlineas_cargas
		{
			get;
		}
		IQueryable<Trzdispositivo> Trzdispositivos
		{
			get;
		}
		IQueryable<Rsocio> Rsocios
		{
			get;
		}
		IQueryable<Rcampo> Rcampos
		{
			get;
		}
		IQueryable<Producto> Productos
		{
			get;
		}
		IQueryable<Trzpalet> Trzpalets
		{
			get;
		}
	}
}
#pragma warning restore 1591
