#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace AriAgrMovModelo	
{
	public partial class Trzpalet
	{
		private uint _idpalet;
		public virtual uint Idpalet
		{
			get
			{
				return this._idpalet;
			}
			set
			{
				this._idpalet = value;
			}
		}
		
		private uint _tipo;
		public virtual uint Tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				this._tipo = value;
			}
		}
		
		private int? _idlote;
		public virtual int? Idlote
		{
			get
			{
				return this._idlote;
			}
			set
			{
				this._idlote = value;
			}
		}
		
		private int? _numcajones;
		public virtual int? Numcajones
		{
			get
			{
				return this._numcajones;
			}
			set
			{
				this._numcajones = value;
			}
		}
		
		private float? _numkilos;
		public virtual float? Numkilos
		{
			get
			{
				return this._numkilos;
			}
			set
			{
				this._numkilos = value;
			}
		}
		
		private int? _idcalle;
		public virtual int? Idcalle
		{
			get
			{
				return this._idcalle;
			}
			set
			{
				this._idcalle = value;
			}
		}
		
		private int? _idarea;
		public virtual int? Idarea
		{
			get
			{
				return this._idarea;
			}
			set
			{
				this._idarea = value;
			}
		}
		
		private int? _codsocio;
		public virtual int? Codsocio
		{
			get
			{
				return this._codsocio;
			}
			set
			{
				this._codsocio = value;
			}
		}
		
		private int? _codcampo;
		public virtual int? Codcampo
		{
			get
			{
				return this._codcampo;
			}
			set
			{
				this._codcampo = value;
			}
		}
		
		private int? _codvarie;
		public virtual int? Codvarie
		{
			get
			{
				return this._codvarie;
			}
			set
			{
				this._codvarie = value;
			}
		}
		
		private DateTime? _fecha;
		public virtual DateTime? Fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				this._fecha = value;
			}
		}
		
		private DateTime? _hora;
		public virtual DateTime? Hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				this._hora = value;
			}
		}
		
		private short? _completo;
		public virtual short? Completo
		{
			get
			{
				return this._completo;
			}
			set
			{
				this._completo = value;
			}
		}
		
		private int _numnotac;
		public virtual int Numnotac
		{
			get
			{
				return this._numnotac;
			}
			set
			{
				this._numnotac = value;
			}
		}
		
		private string _cRFID;
		public virtual string CRFID
		{
			get
			{
				return this._cRFID;
			}
			set
			{
				this._cRFID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
